name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Repo sanity check
        run: |
          echo "CI is running ✅"
          ls -la

      - name: Build
        run: npm run build --if-present
